### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Rusteam** [voxel51/badger#1]
First of all, it's a pretty nifty tool for those who want to generate custom badges!

Things I really liked:
- very concise and organized CLI
- go-wild feature
- clear and easy-to-get-started docs

These issues I faced during my testing:
1. `openai` package commented out and it has to be installed in order to use the package. It can be made optional.
2. Default config file `~/.badger` does not exist. It probable should be a yaml file inside `~/.badger` dir.
3. I faced this error when entering my custom logo urls `xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0`.  If it's possible to print the malformed part of my string, it would be nice.
4. Text prompts can be improved, for instance, indicate which feature is optional (label), where a choice has to be made (badge style), etc.

**Comment by jacobmarks** [comment]
Thanks for the feedback @Rusteam!

Addressed 1. here: #3 
Addressed 2. here: #2 and [here](https://github.com/voxel51/badger/commit/fb78a7816e50bbfc82a32a89e0d5993f08051c52)
Addressed 3. here: #4
